import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const extensionRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.resolve(extensionRoot, '../..');
const packageFile = path.join(extensionRoot, 'package.json');
const version = JSON.parse(fs.readFileSync(packageFile, 'utf8')).version;

if (!/^\d+\.\d+\.\d+$/.test(version)) {
  throw new Error(`Invalid extension version: ${version}`);
}

for (const manifestName of ['manifest.json', 'manifest.development.json']) {
  const manifestFile = path.join(extensionRoot, manifestName);
  const manifestSource = fs.readFileSync(manifestFile, 'utf8');
  const versionField = /("version"\s*:\s*")[^"]+(")/;
  if (!versionField.test(manifestSource)) {
    throw new Error(`Could not find version in ${manifestName}`);
  }
  const updatedManifest = manifestSource.replace(versionField, `$1${version}$2`);
  fs.writeFileSync(manifestFile, updatedManifest);
}

const generatedFile = path.join(repoRoot, 'packages/contracts/src/generated/extension-version.mjs');
fs.mkdirSync(path.dirname(generatedFile), { recursive: true });
fs.writeFileSync(generatedFile, `// Generated by apps/extension/scripts/sync-version.mjs.\nexport const LATEST_EXTENSION_VERSION = '${version}';\n`);
fs.writeFileSync(
  generatedFile.replace(/\.mjs$/, '.d.mts'),
  `// Generated by apps/extension/scripts/sync-version.mjs.\nexport declare const LATEST_EXTENSION_VERSION: string;\n`
);

console.log(`Synchronized extension version ${version}`);
